apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
spec:
  project: default
  source:
    chart: postgresql
    targetRevision: 12.1.2
    repoURL: "https://charts.bitnami.com/bitnami"
    helm:
      values: |
        auth:
          database: G2
          password: senzing
          postgresPassword: postgres
          username: senzing
        
        image:
          pullSecrets:
            - docker.io-secret
          registry: docker.io
          tag: 14.5.0-debian-11-r1
        
        primary:
          persistence:
            enabled: False

  destination:
    server: https://kubernetes.default.svc
    namespace: postgresql
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - Validate=false
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true


