apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: strimzi-kafka-operator
  namespace: argocd
spec:
  project: default
  source:
    chart: strimzi-kafka-operator
    targetRevision: 0.14.0
    repoURL: "https://strimzi.io/charts/"
  destination:
    server: https://kubernetes.default.svc
    namespace: strimzi-kafka-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - Validate=false
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true

